Repository CodeYourFuture/syllabus, pull requests merged in 2020-09, with the labels that each got.

#58 Add Overview Screen
  package-lock.json
  package.json
  src/css/custom.css
  src/pages/index.js
  src/pages/overview.js
  src/pages/styles.module.css
Labels: enhancement

#55 [JS3] Add Array Destructuring to JS3-3 and Remove Classes
  docs/js-core-3/other/javascript-classes.md
  docs/js-core-3/other/this-keyword.md
  docs/js-core-3/week-3/lesson.mdx
  sidebars.js
Labels: JS3, content, enhancement

#61 Strip out conditional installation
  .github/workflows/main.yml
Labels: plumbing

#59 Always use NPM
  .gitignore
  package-lock.json
Labels: plumbing
