Repository CodeYourFuture/syllabus, pull requests merged in 2020-08, with the labels that each got.

#32 [DRAFT] Docusaurus V59
  docs/guides/coding-101.md
  docs/mongodb/week-1/assets/database.png
  docs/mongodb/week-3/assets/operations.png
  docs/node/assets/NoSQL-vs-SQL.png
  docs/node/assets/REST.png
  docs/node/assets/SQL-vs.-NoSQL-Comparative-Advantages-and-Disadvantages.jpg
  docs/node/assets/blog-screenshot.png
  docs/node/assets/http-vs-https.png
  docs/node/assets/http_diagram.png
  docs/node/assets/mongo.png
  docs/node/assets/sql-no-sql-terms.png
  docs/node/assets/vscode-plugin-handlebars.png
  docs/node/assets/workshop.png
  docs/node/week-1/lesson.md
  docs/node/week-2/lesson.md
  docs/workshops/assets/aws/SQL-MongoDB-Correspondence.PNG
  docs/workshops/assets/aws/heroku-mongo.png
  docs/workshops/assets/aws/table-example.png
  docs/workshops/aws-dynamodb-workshop.md
  docusaurus.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: plumbing

#39 Stackoverflow -> Stack Overflow
  .vscode/settings.json
  docs/guides/useful-links.md
  docs/js-core-3/week-1/lesson.md
  docs/workshops/js-testing-workshop.md
  docs/workshops/welcome-to-cyf.md
Labels: content

#45 Fix broken link to contributing guide
  README.md
Labels: bug, content

#36 React hooks updates
  docs/react/assets/data-fetching-timeline-problem.png
  docs/react/assets/data-fetching-timeline-solution.png
  docs/react/assets/when-will-use-effect-be-run.png
  docs/react/week-1/lesson.md
  docs/react/week-2/learning-objectives.md
  docs/react/week-2/lesson.md
  docs/react/week-3/further-reading/container-components.md
  docs/react/week-3/further-reading/multiple-form-fields.md
  docs/react/week-3/learning-objectives.md
  docs/react/week-3/lesson.md
Labels: React, content

#47 Contribution Guide Link Updates
  CONTRIBUTING.md
  README.md
Labels: bug, content
