Repository CodeYourFuture/syllabus, pull requests merged in 2021-01, with the labels that each got.

#139 Add SQL Preparation Docs
  docs/db/assets/Screenshot_Postgres_disk.png
  docs/db/assets/Screenshot_Postgres_initialise.png
  docs/db/assets/Screenshot_Postgres_running.png
  docs/db/prep.md
  docs/db/week-1/lesson.md
  sidebars.js
Labels: SQL

#156 Add code style guide
  docs/guides/assets/prettier-error.png
  docs/guides/code-style-guide.md
  docs/guides/coding-standards.md
  docusaurus.config.js
Labels: enhancement

#163 Add Marking Coursework Lesson Session and Coursework
  docs/git/homework.md
  docs/js-core-1/week-1/homework.md
  docs/js-core-1/week-1/lesson.md
  docs/js-core-1/week-1/mentors.md
  docs/js-core-1/week-2/homework.md
  docs/js-core-1/week-3/homework.md
Labels: JS1

#166 Terminal Lesson
  docs/git/homework.md
  docs/git/overview.md
  docs/git/terminal/assets/git-response.png
  docs/git/terminal/assets/terminal-empty.png
  docs/git/terminal/assets/terminal-error.png
  docs/git/terminal/assets/terminal-example.png
  docs/git/terminal/assets/terminal.png
  docs/git/terminal/assets/viewterminal.png
  docs/git/terminal/assets/windows-desktop.jpg
  docs/git/terminal/assets/windows.png
  docs/git/terminal/homework.md
  docs/git/terminal/lesson.md
  sidebars.js
Labels: Git, Terminal

#174 Some minor Terminal lesson fixes
  docs/git/overview.md
  docs/git/preparation.md
  docs/git/terminal/lesson.md
Labels: Git
