Repository CodeYourFuture/syllabus, pull requests merged in 2021-02, with the labels that each got.

#171 Add "Check Previous Coursework" Task
  docs/js-core-1/week-2/homework.md
  docs/js-core-1/week-3/homework.md
  docs/js-core-2/week-1/homework.md
  docs/js-core-2/week-2/homework.md
  docs/js-core-2/week-3/homework.md
  docs/js-core-3/week-1/homework.md
  docs/js-core-3/week-2/homework.md
  docs/js-core-3/week-3/homework.md
  docs/react/week-1/homework.md
Labels: enhancement

#180 js-3/week-1: Fix copy-paste error in an exercise description
  docs/js-core-3/week-1/lesson.md
Labels: bug, content

#184 js-3/week-2: Add freeCodeCamp tutorial about promises to homework
  docs/js-core-3/week-2/homework.md
Labels: JS3, content
