Repository CodeYourFuture/syllabus, pull requests merged in 2023-01, with the labels that each got.

#555 HTML CSS coursework review
  docs/contributing/minutes.md
  docs/contributing/react/minutes.md
  docs/finalproject/intro.md
  docs/finalproject/prep.md
  docs/finalproject/roles.md
  docs/finalproject/week-1/lesson.md
  docs/finalproject/week-3/lesson.md
  docs/finalproject/week-4/lesson.md
  docs/html-css/week-1/homework.md
  docs/html-css/week-2/homework.md
  docs/html-css/week-3/homework.md
  docs/html-css/week-4/homework.md
  docs/react/week-1/lesson.md
  package-lock.json
Labels: HTML-CSS, content

#558 Update form link and product owner role.md
  docs/finalproject/external-projects.md
Labels: content

#553 Updating presentation
  docs/finalproject/prep.md
Labels: content

#580 PD-HTML/CSS
  docs/html-css/week-1/homework.md
  docs/html-css/week-1/learning-objectives.md
  docs/html-css/week-1/lesson.md
  docs/html-css/week-2/homework.md
  docs/html-css/week-2/learning-objectives.md
  docs/html-css/week-2/lesson.md
  docs/html-css/week-3/homework.md
  docs/html-css/week-3/learning-objectives.md
  docs/html-css/week-3/lesson.md
  docs/html-css/week-4/homework.md
  docs/html-css/week-4/learning-objectives.md
  docs/html-css/week-4/lesson.md
Labels: content

#575 add checklist to pr
  .github/pull_request_template.md
Labels: enhancement

#542 Update External Projects page
  docs/finalproject/external-projects.md
Labels: content
