Repository CodeYourFuture/syllabus, pull requests merged in 2023-02, with the labels that each got.

#612 Adding London 8 project examples
  docs/finalproject/external-projects.md
Labels: content

#609 Adding an overview to this page
  docs/finalproject/week-2/lesson.md
Labels: content

#607 Adding handover document to FP Syllabus
  docs/finalproject/week-4/lesson.md
Labels: content

#608 Add info about a volunteer slack channel
  docs/finalproject/prep.md
Labels: content

#611 Adding new project briefings
  docs/finalproject/projects.md
Labels: content

#594 PD-Git-W1
  docs/git/desktop/homework.md
  docs/git/desktop/lesson.md
Labels: content, Git

#588 PD-JS1-W1
  docs/js-core-1/week-1/homework.md
  docs/js-core-1/week-1/lesson.md
Labels: JS1, content

#590 PD-JS1-W3
  docs/js-core-1/week-3/homework.md
  docs/js-core-1/week-3/lesson.md
Labels: JS1, content

#591 PD-JS1-W4
  docs/js-core-1/week-4/homework.md
  docs/js-core-1/week-4/lesson.md
Labels: JS1, content

#619 PD-JS3-W1
  docs/js-core-3/week-1/homework.md
  docs/js-core-3/week-1/lesson.md
Labels: JS3, content

#617 PD-JS3-W3
  docs/js-core-3/week-3/homework.md
  docs/js-core-3/week-3/lesson.md
Labels: JS3, content

#620 PD-JS3-W4
  docs/js-core-3/week-4/homework.md
  docs/js-core-3/week-4/lesson.md
  docs/js-core-3/week-4/mentors.md
Labels: JS3, content

#618 PD-JS3-W2
  docs/js-core-3/week-2/homework.md
  docs/js-core-3/week-2/lesson.md
Labels: JS3, content

#604 PD-Fund.-W3
  docs/fundamentals/week-3/coursework.md
  docs/fundamentals/week-3/learning-objectives.md
  docs/fundamentals/week-3/session.md
Labels: content, Fundamentals

#603 PD-Fund.-W2
  docs/fundamentals/week-2/coursework.md
  docs/fundamentals/week-2/learning-objectives.md
  docs/fundamentals/week-2/session.md
Labels: content, Fundamentals

#634 PD-Node-W1
  docs/node/week-1/homework.md
  docs/node/week-1/lesson.md
Labels: Node, content

#635 PD-Node-W2
  docs/node/week-2/homework.md
  docs/node/week-2/lesson.md
Labels: Node, content

#632 Adding information about tracking performance FP
  docs/finalproject/week-1/lesson.md
Labels: content

#631 Adding tracker information to criteria
  docs/finalproject/intro.md
Labels: content

#630 Adding cooling period to Week 2 FP
  docs/finalproject/week-2/lesson.md
Labels: content

#636 PD-Node-W3
  docs/node/week-3/lesson.md
Labels: Node, content

#610 Adding overview and cooling period information
  docs/finalproject/week-3/lesson.md
Labels: content
